{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toast-cmp/0.1.0/toast-cmp-0.1.0.module",
    "group": "io.github.gycrosskit",
    "module": "toast-cmp",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.github.gycrosskit",
          "module": "toast",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21-1.0.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        }
      ],
      "files": [
        {
          "name": "toast-cmp-iosSimulatorArm64Main-0.1.0.klib",
          "url": "toast-cmp-iossimulatorarm64-0.1.0.klib",
          "size": 7248,
          "sha512": "71bb40c4c3c8cebe0d434340ca40507681bfc8e5661165eaf08a041b7975f8bb157f2ee8391d57cc51a9fede8428bbe897085ec6e25147b72dab564951463542",
          "sha256": "619ea93cd5311d8081301c0c4d33940d9263a415c43eedbb9e81944a5b1e05ca",
          "sha1": "9a7968a5f192827c67945384cd343c8e0debaac0",
          "md5": "38c4a60a010a13ae17eea4998d6309f2"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "toast-cmp-iossimulatorarm64-0.1.0-sources.jar",
          "url": "toast-cmp-iossimulatorarm64-0.1.0-sources.jar",
          "size": 1498,
          "sha512": "19e09c9c929948f473c2a38eb72546c47e1beb31d4d376bd27da77bec58dde37724c7175edaf48bc9e02339a3ac3ecf475cc514ac6aafe9dfb7c6d712b0e3404",
          "sha256": "6d75a64a729a0b6237b037298d6d12577a83b4d63f2c23309ac8af4c3dd5fec3",
          "sha1": "e1d4ffc61db3087da6810ed032f93d3454317872",
          "md5": "4863860849fd1f9b3e78c847faa9fd26"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.github.gycrosskit",
          "module": "toast",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21-1.0.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        }
      ],
      "files": [
        {
          "name": "toast-cmp-0.1.0.kotlin_resources.zip",
          "url": "toast-cmp-iossimulatorarm64-0.1.0-kotlin_resources.kotlin_resources.zip",
          "size": 348,
          "sha512": "fb250cd2778029b75d92c3ee70e8dba1c4e720fd0e21768b2dba8dbdc333d756e2f2ea219fe65c2fe38a5615082514b9f8494a7787b809fe6f3dea68fc1106fe",
          "sha256": "65b5daa8448bf2680ad789d06d55f397f409d94fda47fcfad85176601ca5ebb2",
          "sha1": "00611c0f8620e75fb766cda538299e5f8ba5d10b",
          "md5": "5e0537d5531ab44793e44cb07c492844"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.github.gycrosskit",
          "module": "toast",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21-1.0.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        }
      ],
      "files": [
        {
          "name": "toast-cmp-iossimulatorarm64-0.1.0-metadata.jar",
          "url": "toast-cmp-iossimulatorarm64-0.1.0-metadata.jar",
          "size": 261,
          "sha512": "920e5f35ffed7df5fbc1a6b9cafcc02a51d939fdf881b699df1bfb0cb95d93e8c6a8dc497e7449d71a9d16a65c635c00e14e19de44f607ef3ec726c26cb4ad89",
          "sha256": "3f47166717bb2591d39410e3474b1796ce41810071980a1ee15f438b86d6cc68",
          "sha1": "c055444a2d9597665b260a0d981bd27ba1e038a7",
          "md5": "b25d5d0ad50a49043b0016a50ba50d59"
        }
      ]
    }
  ]
}
