{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toast-kuikly/0.1.0/toast-kuikly-0.1.0.module",
    "group": "io.github.gycrosskit",
    "module": "toast-kuikly",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "ohosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ohos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.github.gycrosskit",
          "module": "toast",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21-1.0.0"
          }
        },
        {
          "group": "com.tencent.kuikly-open",
          "module": "core",
          "version": {
            "requires": "2.28.0-2.0.21-ohos"
          }
        }
      ],
      "files": [
        {
          "name": "toast-kuikly-ohosArm64Main-0.1.0.klib",
          "url": "toast-kuikly-ohosarm64-0.1.0.klib",
          "size": 5842,
          "sha512": "63cf3acf29eb8b888df547eefbe93d1f319cc3302a396fef09b94dba9a7cf58d9fd8558baeba58efe30781319e54e8f0cd58cedd6b2bafd5087faaf048b25e8b",
          "sha256": "174efc7058e5ec2cc32cdf3127b61b476d201619717a0ee20a7325bafb841d4c",
          "sha1": "16fe6ca302d8b5c5e20f8af2eb4d62f3d4a2db12",
          "md5": "d8648343892defafd4605f6f1f6cd16f"
        }
      ]
    },
    {
      "name": "ohosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ohos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "toast-kuikly-ohosarm64-0.1.0-sources.jar",
          "url": "toast-kuikly-ohosarm64-0.1.0-sources.jar",
          "size": 1701,
          "sha512": "7c75abf209f00f7b97c82911e2ca58b9866743903d8adc3d47ed602b871328ebb11df1e504cef434e703f87b1924ac0e12b6539cb38ae2556d464bd0b4044428",
          "sha256": "5298a378020e2fd2ecdc12aaab05dc48a25bfef125aed7c271d85674b074b9ff",
          "sha1": "14ee505b4c42df66d273e92132691f3a365f6e81",
          "md5": "267fbdf8e8657a2821831abf5cba0521"
        }
      ]
    }
  ]
}
