{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toast/0.1.0/toast-0.1.0.module",
    "group": "io.github.gycrosskit",
    "module": "toast",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21-1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "toast-release.aar",
          "url": "toast-android-0.1.0.aar",
          "size": 6885,
          "sha512": "43fd092b218e546439362299d257393d69ede426ef35aa2a663a0c6db351ced962917a0051d79a3955c63e78ce93cab837f2ffba8de71f87754797821d02fdc2",
          "sha256": "e12496439f8cfebaa440469fe1378261bad68a10480f7384ac3616e673463f67",
          "sha1": "4ad09d3ff33a82acdc3dbdf9a74b7732d2519f61",
          "md5": "2b2f24158c5e7dca8a9dbea753acad64"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21-1.0.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "toast-release.aar",
          "url": "toast-android-0.1.0.aar",
          "size": 6885,
          "sha512": "43fd092b218e546439362299d257393d69ede426ef35aa2a663a0c6db351ced962917a0051d79a3955c63e78ce93cab837f2ffba8de71f87754797821d02fdc2",
          "sha256": "e12496439f8cfebaa440469fe1378261bad68a10480f7384ac3616e673463f67",
          "sha1": "4ad09d3ff33a82acdc3dbdf9a74b7732d2519f61",
          "md5": "2b2f24158c5e7dca8a9dbea753acad64"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "toast-android-0.1.0-sources.jar",
          "url": "toast-android-0.1.0-sources.jar",
          "size": 2874,
          "sha512": "52502f05c1f51fb193d269d8d2f52960e3a1ab76f7955858f474a36c667c42f5386d49f3dff8cddcef4c5c9e1bd0318544bcdf70279f5c6a4540472fa0a14b5d",
          "sha256": "419361234b6d3a49a3ae13bb8a2ad009c121c95d972eb1668845633627443063",
          "sha1": "ae575912b7c60d2bdda6d3eaf0972c76e7c82bd3",
          "md5": "5183ce6779b54c9bfa387b66c04d1b81"
        }
      ]
    }
  ]
}
