{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gycrosskit",
    "module": "toast",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21-1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "toast-metadata-0.1.0.jar",
          "url": "toast-0.1.0.jar",
          "size": 2453,
          "sha512": "6e3bccd214676964e44b00012bdea2ade026613084be58146dcc29ccf25941b13106f3e018aac115ecb879701c440f03292b6286845d57050aefe691f901ae4e",
          "sha256": "de366a16f8b9e4bee054215ddc03cdfa2385ab1c6924fccf2acc1325d061b885",
          "sha1": "d5372629851937edcc9d8dbfc27509aea044e93c",
          "md5": "e9d38960fa3286ee089b386536469b8e"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "toast-kotlin-0.1.0-sources.jar",
          "url": "toast-0.1.0-sources.jar",
          "size": 2423,
          "sha512": "76ffbba27e42e2cd9a7f21bcb2f10ea2be07abf868281d30896996711c6d64a78521a7848fecc5cb0ec9a92e49e722ebcf7012ad65b424f1eb4a422a7991babe",
          "sha256": "98806c3160a1291306657b0b1638f97d651053104c992bf0e093ce0d328a998a",
          "sha1": "9e8e49cb9763429748daf241bec69a15309e8178",
          "md5": "ba61bec312424670594cc456a8962e90"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../toast-android/0.1.0/toast-android-0.1.0.module",
        "group": "io.github.gycrosskit",
        "module": "toast-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../toast-android/0.1.0/toast-android-0.1.0.module",
        "group": "io.github.gycrosskit",
        "module": "toast-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../toast-android/0.1.0/toast-android-0.1.0.module",
        "group": "io.github.gycrosskit",
        "module": "toast-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../toast-iosarm64/0.1.0/toast-iosarm64-0.1.0.module",
        "group": "io.github.gycrosskit",
        "module": "toast-iosarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../toast-iosarm64/0.1.0/toast-iosarm64-0.1.0.module",
        "group": "io.github.gycrosskit",
        "module": "toast-iosarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../toast-iosarm64/0.1.0/toast-iosarm64-0.1.0.module",
        "group": "io.github.gycrosskit",
        "module": "toast-iosarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../toast-iossimulatorarm64/0.1.0/toast-iossimulatorarm64-0.1.0.module",
        "group": "io.github.gycrosskit",
        "module": "toast-iossimulatorarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../toast-iossimulatorarm64/0.1.0/toast-iossimulatorarm64-0.1.0.module",
        "group": "io.github.gycrosskit",
        "module": "toast-iossimulatorarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../toast-iossimulatorarm64/0.1.0/toast-iossimulatorarm64-0.1.0.module",
        "group": "io.github.gycrosskit",
        "module": "toast-iossimulatorarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../toast-iosx64/0.1.0/toast-iosx64-0.1.0.module",
        "group": "io.github.gycrosskit",
        "module": "toast-iosx64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../toast-iosx64/0.1.0/toast-iosx64-0.1.0.module",
        "group": "io.github.gycrosskit",
        "module": "toast-iosx64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../toast-iosx64/0.1.0/toast-iosx64-0.1.0.module",
        "group": "io.github.gycrosskit",
        "module": "toast-iosx64",
        "version": "0.1.0"
      }
    },
    {
      "name": "ohosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ohos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../toast-ohosarm64/0.1.0/toast-ohosarm64-0.1.0.module",
        "group": "io.github.gycrosskit",
        "module": "toast-ohosarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "ohosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ohos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../toast-ohosarm64/0.1.0/toast-ohosarm64-0.1.0.module",
        "group": "io.github.gycrosskit",
        "module": "toast-ohosarm64",
        "version": "0.1.0"
      }
    }
  ]
}
