{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gycrosskit",
    "module": "toast-cmp",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "io.github.gycrosskit",
          "module": "toast",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21-1.0.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        }
      ],
      "files": [
        {
          "name": "toast-cmp-metadata-0.1.0.jar",
          "url": "toast-cmp-0.1.0.jar",
          "size": 2519,
          "sha512": "81bb6e107f7ddf4fd55e7c438ba384e7d5c478f3902da4aaef93d7bb5704e97cf2dce31ab27776d6efe7cc7f704a2abca2a384fd8d7fca924b271ca192bacd5c",
          "sha256": "13a4acf2ec30275fdd6de8581c56f54b660c3f70cfb7bda496e3e2cc510ae265",
          "sha1": "7ae44067f2dc85299af16643ac3c0aa66283ea4a",
          "md5": "7fb535ef8eef27817144677a937cee13"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "toast-cmp-kotlin-0.1.0-sources.jar",
          "url": "toast-cmp-0.1.0-sources.jar",
          "size": 1498,
          "sha512": "19e09c9c929948f473c2a38eb72546c47e1beb31d4d376bd27da77bec58dde37724c7175edaf48bc9e02339a3ac3ecf475cc514ac6aafe9dfb7c6d712b0e3404",
          "sha256": "6d75a64a729a0b6237b037298d6d12577a83b4d63f2c23309ac8af4c3dd5fec3",
          "sha1": "e1d4ffc61db3087da6810ed032f93d3454317872",
          "md5": "4863860849fd1f9b3e78c847faa9fd26"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../toast-cmp-android/0.1.0/toast-cmp-android-0.1.0.module",
        "group": "io.github.gycrosskit",
        "module": "toast-cmp-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../toast-cmp-android/0.1.0/toast-cmp-android-0.1.0.module",
        "group": "io.github.gycrosskit",
        "module": "toast-cmp-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../toast-cmp-android/0.1.0/toast-cmp-android-0.1.0.module",
        "group": "io.github.gycrosskit",
        "module": "toast-cmp-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../toast-cmp-iosarm64/0.1.0/toast-cmp-iosarm64-0.1.0.module",
        "group": "io.github.gycrosskit",
        "module": "toast-cmp-iosarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../toast-cmp-iosarm64/0.1.0/toast-cmp-iosarm64-0.1.0.module",
        "group": "io.github.gycrosskit",
        "module": "toast-cmp-iosarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../toast-cmp-iosarm64/0.1.0/toast-cmp-iosarm64-0.1.0.module",
        "group": "io.github.gycrosskit",
        "module": "toast-cmp-iosarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../toast-cmp-iosarm64/0.1.0/toast-cmp-iosarm64-0.1.0.module",
        "group": "io.github.gycrosskit",
        "module": "toast-cmp-iosarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../toast-cmp-iossimulatorarm64/0.1.0/toast-cmp-iossimulatorarm64-0.1.0.module",
        "group": "io.github.gycrosskit",
        "module": "toast-cmp-iossimulatorarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../toast-cmp-iossimulatorarm64/0.1.0/toast-cmp-iossimulatorarm64-0.1.0.module",
        "group": "io.github.gycrosskit",
        "module": "toast-cmp-iossimulatorarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../toast-cmp-iossimulatorarm64/0.1.0/toast-cmp-iossimulatorarm64-0.1.0.module",
        "group": "io.github.gycrosskit",
        "module": "toast-cmp-iossimulatorarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../toast-cmp-iossimulatorarm64/0.1.0/toast-cmp-iossimulatorarm64-0.1.0.module",
        "group": "io.github.gycrosskit",
        "module": "toast-cmp-iossimulatorarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../toast-cmp-iosx64/0.1.0/toast-cmp-iosx64-0.1.0.module",
        "group": "io.github.gycrosskit",
        "module": "toast-cmp-iosx64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../toast-cmp-iosx64/0.1.0/toast-cmp-iosx64-0.1.0.module",
        "group": "io.github.gycrosskit",
        "module": "toast-cmp-iosx64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../toast-cmp-iosx64/0.1.0/toast-cmp-iosx64-0.1.0.module",
        "group": "io.github.gycrosskit",
        "module": "toast-cmp-iosx64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../toast-cmp-iosx64/0.1.0/toast-cmp-iosx64-0.1.0.module",
        "group": "io.github.gycrosskit",
        "module": "toast-cmp-iosx64",
        "version": "0.1.0"
      }
    }
  ]
}
