{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toast-cmp/0.1.0/toast-cmp-0.1.0.module",
    "group": "io.github.gycrosskit",
    "module": "toast-cmp",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.github.gycrosskit",
          "module": "toast",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21-1.0.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        }
      ],
      "files": [
        {
          "name": "toast-cmp-iosX64Main-0.1.0.klib",
          "url": "toast-cmp-iosx64-0.1.0.klib",
          "size": 7170,
          "sha512": "fbfc0a2f0cf64671aab134947daf7e84daf53ff4fe672e6e829e11661c6d81018ff80403f05815913f579e92c7f93fcf2e2ef6a65da12964407c03a6ab7e61f2",
          "sha256": "c065e145f94980a44ad607b32e04d92ec9250c5e9b079d26335d27ded3cfa734",
          "sha1": "67f67ffaa1a7a2591f2579e29726552e679fd64d",
          "md5": "abd395175d2b6c203f3580448535f2b5"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "toast-cmp-iosx64-0.1.0-sources.jar",
          "url": "toast-cmp-iosx64-0.1.0-sources.jar",
          "size": 1498,
          "sha512": "19e09c9c929948f473c2a38eb72546c47e1beb31d4d376bd27da77bec58dde37724c7175edaf48bc9e02339a3ac3ecf475cc514ac6aafe9dfb7c6d712b0e3404",
          "sha256": "6d75a64a729a0b6237b037298d6d12577a83b4d63f2c23309ac8af4c3dd5fec3",
          "sha1": "e1d4ffc61db3087da6810ed032f93d3454317872",
          "md5": "4863860849fd1f9b3e78c847faa9fd26"
        }
      ]
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.github.gycrosskit",
          "module": "toast",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21-1.0.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        }
      ],
      "files": [
        {
          "name": "toast-cmp-0.1.0.kotlin_resources.zip",
          "url": "toast-cmp-iosx64-0.1.0-kotlin_resources.kotlin_resources.zip",
          "size": 348,
          "sha512": "1e0ce3eede0c6d31de44116619b24f292f3121d66e767dc13d62762079faa62e4153f904002e95f459b080bae21554695bc8f476921047254a3e233939f11372",
          "sha256": "1987ef6c9e8050405d9c2cd1e2e7022ad06f376fdcbc6bde71ffa7c8fe0318f0",
          "sha1": "d15279f8b210e2319fc4498c7c28ca2331f1fe36",
          "md5": "73a7537e68bf67cd217c908401275501"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.github.gycrosskit",
          "module": "toast",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21-1.0.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        }
      ],
      "files": [
        {
          "name": "toast-cmp-iosx64-0.1.0-metadata.jar",
          "url": "toast-cmp-iosx64-0.1.0-metadata.jar",
          "size": 261,
          "sha512": "75c076f564fc16a0c26d065165e01c0b0e209671601900d88fb6a089576e0392c1935845d6d65788a4dc70fefae6d9d5d2b6638fbbb1cf7acefec07fbf86238b",
          "sha256": "6f9a07bf3eebb84fc66bacc1b4c3d9a3de6801e895dcd60a8af8f09d2474fcde",
          "sha1": "f02e4aa8607a5150aa5036b1f298faf916c44279",
          "md5": "fafa2ed2020d3a5aa6693e91ca392c39"
        }
      ]
    }
  ]
}
