{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gycrosskit",
    "module": "toast-kuikly",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "io.github.gycrosskit",
          "module": "toast",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21-1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "toast-kuikly-metadata-0.1.0.jar",
          "url": "toast-kuikly-0.1.0.jar",
          "size": 667,
          "sha512": "cce1821a4e8280577d119d94b02f6dc097104f9768de8966b8f6ac0b42dbd27e443c37f64ae4e5f840113ed9c3d77cef527425aee7baaca1fb9aec413c01be6d",
          "sha256": "77d5c01535294de771c0c3e7be3519bbb2118f6b73a05503bdfa53d8e680f05b",
          "sha1": "5c7246977975bdb7ae6dcb4fc75bf8bc36106e17",
          "md5": "827c3173eee2dfe015ff1f580b34b9fc"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "toast-kuikly-kotlin-0.1.0-sources.jar",
          "url": "toast-kuikly-0.1.0-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "ohosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ohos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../toast-kuikly-ohosarm64/0.1.0/toast-kuikly-ohosarm64-0.1.0.module",
        "group": "io.github.gycrosskit",
        "module": "toast-kuikly-ohosarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "ohosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ohos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../toast-kuikly-ohosarm64/0.1.0/toast-kuikly-ohosarm64-0.1.0.module",
        "group": "io.github.gycrosskit",
        "module": "toast-kuikly-ohosarm64",
        "version": "0.1.0"
      }
    }
  ]
}
