{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toast-cmp/0.1.0/toast-cmp-0.1.0.module",
    "group": "io.github.gycrosskit",
    "module": "toast-cmp",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.github.gycrosskit",
          "module": "toast",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21-1.0.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        }
      ],
      "files": [
        {
          "name": "toast-cmp-iosArm64Main-0.1.0.klib",
          "url": "toast-cmp-iosarm64-0.1.0.klib",
          "size": 7183,
          "sha512": "13d499bc0912b30be0d36eeb8691431c8bb5a66999047555b9513496c3ec377a497aa1187502e95ba149ff713922cb0acab61ca41fea301723e20851f6473b7b",
          "sha256": "920c49ccf4ac94fb7501a2699bc6d3ad97edc263608a4cf2310ee1346838dcff",
          "sha1": "a2c4064ab7ee7f736867b12697233b40b4dcd752",
          "md5": "e009549586e9f5c69850381de0be03bc"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "toast-cmp-iosarm64-0.1.0-sources.jar",
          "url": "toast-cmp-iosarm64-0.1.0-sources.jar",
          "size": 1498,
          "sha512": "19e09c9c929948f473c2a38eb72546c47e1beb31d4d376bd27da77bec58dde37724c7175edaf48bc9e02339a3ac3ecf475cc514ac6aafe9dfb7c6d712b0e3404",
          "sha256": "6d75a64a729a0b6237b037298d6d12577a83b4d63f2c23309ac8af4c3dd5fec3",
          "sha1": "e1d4ffc61db3087da6810ed032f93d3454317872",
          "md5": "4863860849fd1f9b3e78c847faa9fd26"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.github.gycrosskit",
          "module": "toast",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21-1.0.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        }
      ],
      "files": [
        {
          "name": "toast-cmp-0.1.0.kotlin_resources.zip",
          "url": "toast-cmp-iosarm64-0.1.0-kotlin_resources.kotlin_resources.zip",
          "size": 348,
          "sha512": "69ed3e8940e758685061ebdf8fb3cd6cc6f9e22801944c6fc7de8afa5e5ef0b69346c1369a1f44018b24794c7bd4bb9cfbd6a5fa4911f23ee362f6712532e0f8",
          "sha256": "a82fce8fb2ba41029bd40a488f198096910b99642ac92cc389b9ec23ed325893",
          "sha1": "f1e27e53a3dae6adcb80732ef0f8e62554c337c6",
          "md5": "83d318a1226982cf1f608f0f50619e11"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.github.gycrosskit",
          "module": "toast",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21-1.0.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        }
      ],
      "files": [
        {
          "name": "toast-cmp-iosarm64-0.1.0-metadata.jar",
          "url": "toast-cmp-iosarm64-0.1.0-metadata.jar",
          "size": 261,
          "sha512": "fd73058cdb5df8f5281605bde4bfc22593255b6c24fd80d4dec4843276c4aa612892e1b256cce45567f0bf9e2d3961740995deb0b9543c1155fafe6e6f144aa5",
          "sha256": "26b39e4a7d6696766d868968f3fe9f0c434badcb7005bf2fca4133a862bfffd6",
          "sha1": "9a313f45bde8fddd3c5c89332ad28e48eb2c05cb",
          "md5": "a850383579803ff1d0acf07a36539ac5"
        }
      ]
    }
  ]
}
